// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Moved from the 'meettheneeds' project to 'myn-sales'. The seller app is
  // registered there as com.meetyoureneeds.seller (the spelling Play Console
  // permanently assigned to this listing), and the service-account key
  // the backend pushes with belongs to that project — an FCM send only reaches
  // devices registered under the same project as the sender.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NcoVOlboGfzoeKGDDtT6FkNsuicjLYU',
    appId: '1:357882681208:android:8dc49288f5da150383da8d',
    messagingSenderId: '357882681208',
    projectId: 'myn-sales',
    storageBucket: 'myn-sales.appspot.com',
  );

  // Deliberately still on 'meettheneeds': iOS has no Firebase app in myn-sales
  // and no APNs key uploaded, so push does not work there yet. These values
  // match ios/Runner/GoogleService-Info.plist — change both together when the
  // iOS side is set up.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFVXkIzM52E2DawDsDboyKuErRmPYP0ww',
    appId: '1:865321195733:ios:5d687eadb58ceb76456a5c',
    messagingSenderId: '865321195733',
    projectId: 'meettheneeds',
    storageBucket: 'meettheneeds.appspot.com',
    androidClientId:
        '865321195733-6hfp9qa2uvuka5t8p40jadousror02ms.apps.googleusercontent.com',
    iosBundleId: 'com.meettheneeds.seller',
  );
}
